Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,3 +31,27 @@ jobs:
 
       - name: List directory contents
         run: ls -la
+      - name: Create SSH directory and known_hosts file
+        run: |
+          mkdir -p ~/.ssh
+          touch ~/.ssh/known_hosts
+          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
+        shell: /usr/bin/bash -e {0}
+
+      - name: Deploy to Tomcat Server
+        env:
+          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.11-9/x64
+          SERVER_IP: ${{ secrets.SERVER_IP }}
+          USERNAME: ${{ secrets.USERNAME }}
+          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
+          TOMCAT_DIR: ${{ secrets.TOMCAT_DIR }}
+        run: |
+          echo "Preparing to deploy to server..."
+          echo "Using SERVER_IP: $SERVER_IP"
+          echo "Using USERNAME: $USERNAME"
+          
+          echo "$PRIVATE_KEY" > private_key.pem
+          chmod 600 private_key.pem
+          
+          echo "Attempting SCP transfer..."
+          scp -i private_key.pem package.tar.gz $USERNAME@$SERVER_IP:/tmp/ || { echo "SCP failed"; exit 1; }
